### ISSUE TITLE
[Tracking] Release a first version as Bootstrap `main` branch

### ISSUE THREAD

**Issue by julien-deramond** [julien-deramond/bootstrap-sandbox#3]
### Description

Before starting experiment things, this library needs to generate exactly the same files as Bootstrap. Here are some remaining tasks before considering that we're ready to go.

- [x] Our `bootstrap-sandbox.css` contains the source map as a `data:application/json;base64` instead of an external map file
- [x] ~Some `dist/*.css` contains an extra unwanted `@charset "UTF-8";` at the top compared to Bootstrap. For some others, they are already like that in Bootstrap 🤷~: might not be an issue after all. Let's try like that.
- [x] Put in place JavaScript files, compilation, and generate all JavaScript files
- [ ] Put in place the release system
